#ifndef SQL_FIELDNAME_H
#define SQL_FIELDNAME_H

#define F_SOLDIERID         "f_soldierid"
#define F_SOLDIERNAME       "f_soldiername"
#define F_SOLDIERTYPE       "f_soldiertype"
#define F_RANK              "f_rank"
#define F_LEVEL             "f_level"
#define F_POST              "f_post"
#define F_BIRTHDAY          "f_birthday"
#define F_ARMYDAY           "f_armyday"
#define F_SEX               "f_sex"
#define F_NATION            "f_nation"
#define F_NATIVEPLACE       "f_nativeplace"
#define F_POLITICS          "f_politics"
#define F_IDTYPE            "f_idtype"
#define F_IDNUMBER          "f_idnumber"
#define F_UNITID            "f_unitid"
#define F_LEADER            "f_leader"
#define F_PASSWORD          "f_password"
#define F_SOLDIERENABLE     "f_soldierenable"
#define F_PSWERRORS         "f_pswerrors"
#define F_LOGINID           "f_loginid"
#define F_ONLINE            "f_online"
#define F_SOLDIERTYPENAME   "f_soldiertypename"
#define F_RANKNAME          "f_rankname"
#define F_LEVELNAME         "f_levelname"
#define F_POSTNAME          "f_postname"
#define F_SEXNAME           "f_sexname"
#define F_NATIONNAME        "f_nationname"
#define F_POLITICSNAME      "f_politicsname"
#define F_IDTYPENAME        "f_idtypename"
#define F_UNITNAME          "f_unitname"
#define F_UNITSHORTNAME     "f_unitshortname"
#define F_CURLONGITUDE      "f_curlongitude"
#define F_CURLATITUDE       "f_curlatitude"

#endif // SQL_FIELDNAME_H
