// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fusion.proto

#ifndef PROTOBUF_INCLUDED_fusion_2eproto
#define PROTOBUF_INCLUDED_fusion_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_fusion_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_fusion_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_fusion_2eproto();
namespace fusionPackage {
class Timestamp;
class TimestampDefaultTypeInternal;
extern TimestampDefaultTypeInternal _Timestamp_default_instance_;
class fusionMsg;
class fusionMsgDefaultTypeInternal;
extern fusionMsgDefaultTypeInternal _fusionMsg_default_instance_;
class targetMessage;
class targetMessageDefaultTypeInternal;
extern targetMessageDefaultTypeInternal _targetMessage_default_instance_;
}  // namespace fusionPackage
namespace google {
namespace protobuf {
template<> ::fusionPackage::Timestamp* Arena::CreateMaybeMessage<::fusionPackage::Timestamp>(Arena*);
template<> ::fusionPackage::fusionMsg* Arena::CreateMaybeMessage<::fusionPackage::fusionMsg>(Arena*);
template<> ::fusionPackage::targetMessage* Arena::CreateMaybeMessage<::fusionPackage::targetMessage>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace fusionPackage {

// ===================================================================

class targetMessage final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fusionPackage.targetMessage) */ {
 public:
  targetMessage();
  virtual ~targetMessage();

  targetMessage(const targetMessage& from);

  inline targetMessage& operator=(const targetMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  targetMessage(targetMessage&& from) noexcept
    : targetMessage() {
    *this = ::std::move(from);
  }

  inline targetMessage& operator=(targetMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const targetMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const targetMessage* internal_default_instance() {
    return reinterpret_cast<const targetMessage*>(
               &_targetMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(targetMessage* other);
  friend void swap(targetMessage& a, targetMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline targetMessage* New() const final {
    return CreateMaybeMessage<targetMessage>(nullptr);
  }

  targetMessage* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<targetMessage>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const targetMessage& from);
  void MergeFrom(const targetMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(targetMessage* other);
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::google::protobuf::StringPiece FullMessageName() {
    return "fusionPackage.targetMessage";
  }
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 lon = 2;
  bool has_lon() const;
  void clear_lon();
  static const int kLonFieldNumber = 2;
  ::google::protobuf::uint64 lon() const;
  void set_lon(::google::protobuf::uint64 value);

  // required uint32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // required int32 velocity = 4;
  bool has_velocity() const;
  void clear_velocity();
  static const int kVelocityFieldNumber = 4;
  ::google::protobuf::int32 velocity() const;
  void set_velocity(::google::protobuf::int32 value);

  // required uint64 lat = 3;
  bool has_lat() const;
  void clear_lat();
  static const int kLatFieldNumber = 3;
  ::google::protobuf::uint64 lat() const;
  void set_lat(::google::protobuf::uint64 value);

  // required int32 heading = 5;
  bool has_heading() const;
  void clear_heading();
  static const int kHeadingFieldNumber = 5;
  ::google::protobuf::int32 heading() const;
  void set_heading(::google::protobuf::int32 value);

  // required uint32 type = 6;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 6;
  ::google::protobuf::uint32 type() const;
  void set_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:fusionPackage.targetMessage)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint64 lon_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::int32 velocity_;
  ::google::protobuf::uint64 lat_;
  ::google::protobuf::int32 heading_;
  ::google::protobuf::uint32 type_;
  friend struct ::TableStruct_fusion_2eproto;
};
// -------------------------------------------------------------------

class Timestamp final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fusionPackage.Timestamp) */ {
 public:
  Timestamp();
  virtual ~Timestamp();

  Timestamp(const Timestamp& from);

  inline Timestamp& operator=(const Timestamp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Timestamp(Timestamp&& from) noexcept
    : Timestamp() {
    *this = ::std::move(from);
  }

  inline Timestamp& operator=(Timestamp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Timestamp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Timestamp* internal_default_instance() {
    return reinterpret_cast<const Timestamp*>(
               &_Timestamp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Timestamp* other);
  friend void swap(Timestamp& a, Timestamp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Timestamp* New() const final {
    return CreateMaybeMessage<Timestamp>(nullptr);
  }

  Timestamp* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Timestamp>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Timestamp& from);
  void MergeFrom(const Timestamp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Timestamp* other);
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::google::protobuf::StringPiece FullMessageName() {
    return "fusionPackage.Timestamp";
  }
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 seconds = 1;
  bool has_seconds() const;
  void clear_seconds();
  static const int kSecondsFieldNumber = 1;
  ::google::protobuf::int64 seconds() const;
  void set_seconds(::google::protobuf::int64 value);

  // required int32 nanos = 2;
  bool has_nanos() const;
  void clear_nanos();
  static const int kNanosFieldNumber = 2;
  ::google::protobuf::int32 nanos() const;
  void set_nanos(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:fusionPackage.Timestamp)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int64 seconds_;
  ::google::protobuf::int32 nanos_;
  friend struct ::TableStruct_fusion_2eproto;
};
// -------------------------------------------------------------------

class fusionMsg final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fusionPackage.fusionMsg) */ {
 public:
  fusionMsg();
  virtual ~fusionMsg();

  fusionMsg(const fusionMsg& from);

  inline fusionMsg& operator=(const fusionMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  fusionMsg(fusionMsg&& from) noexcept
    : fusionMsg() {
    *this = ::std::move(from);
  }

  inline fusionMsg& operator=(fusionMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const fusionMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const fusionMsg* internal_default_instance() {
    return reinterpret_cast<const fusionMsg*>(
               &_fusionMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(fusionMsg* other);
  friend void swap(fusionMsg& a, fusionMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline fusionMsg* New() const final {
    return CreateMaybeMessage<fusionMsg>(nullptr);
  }

  fusionMsg* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<fusionMsg>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const fusionMsg& from);
  void MergeFrom(const fusionMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(fusionMsg* other);
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::google::protobuf::StringPiece FullMessageName() {
    return "fusionPackage.fusionMsg";
  }
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .fusionPackage.targetMessage msg = 2;
  int msg_size() const;
  void clear_msg();
  static const int kMsgFieldNumber = 2;
  ::fusionPackage::targetMessage* mutable_msg(int index);
  ::google::protobuf::RepeatedPtrField< ::fusionPackage::targetMessage >*
      mutable_msg();
  const ::fusionPackage::targetMessage& msg(int index) const;
  ::fusionPackage::targetMessage* add_msg();
  const ::google::protobuf::RepeatedPtrField< ::fusionPackage::targetMessage >&
      msg() const;

  // required .fusionPackage.Timestamp timeStamp = 1;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimeStampFieldNumber = 1;
  const ::fusionPackage::Timestamp& timestamp() const;
  ::fusionPackage::Timestamp* release_timestamp();
  ::fusionPackage::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::fusionPackage::Timestamp* timestamp);

  // @@protoc_insertion_point(class_scope:fusionPackage.fusionMsg)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::fusionPackage::targetMessage > msg_;
  ::fusionPackage::Timestamp* timestamp_;
  friend struct ::TableStruct_fusion_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// targetMessage

// required uint32 id = 1;
inline bool targetMessage::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void targetMessage::clear_id() {
  id_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::uint32 targetMessage::id() const {
  // @@protoc_insertion_point(field_get:fusionPackage.targetMessage.id)
  return id_;
}
inline void targetMessage::set_id(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000002u;
  id_ = value;
  // @@protoc_insertion_point(field_set:fusionPackage.targetMessage.id)
}

// required uint64 lon = 2;
inline bool targetMessage::has_lon() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void targetMessage::clear_lon() {
  lon_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::uint64 targetMessage::lon() const {
  // @@protoc_insertion_point(field_get:fusionPackage.targetMessage.lon)
  return lon_;
}
inline void targetMessage::set_lon(::google::protobuf::uint64 value) {
  _has_bits_[0] |= 0x00000001u;
  lon_ = value;
  // @@protoc_insertion_point(field_set:fusionPackage.targetMessage.lon)
}

// required uint64 lat = 3;
inline bool targetMessage::has_lat() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void targetMessage::clear_lat() {
  lat_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000008u;
}
inline ::google::protobuf::uint64 targetMessage::lat() const {
  // @@protoc_insertion_point(field_get:fusionPackage.targetMessage.lat)
  return lat_;
}
inline void targetMessage::set_lat(::google::protobuf::uint64 value) {
  _has_bits_[0] |= 0x00000008u;
  lat_ = value;
  // @@protoc_insertion_point(field_set:fusionPackage.targetMessage.lat)
}

// required int32 velocity = 4;
inline bool targetMessage::has_velocity() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void targetMessage::clear_velocity() {
  velocity_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::int32 targetMessage::velocity() const {
  // @@protoc_insertion_point(field_get:fusionPackage.targetMessage.velocity)
  return velocity_;
}
inline void targetMessage::set_velocity(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  velocity_ = value;
  // @@protoc_insertion_point(field_set:fusionPackage.targetMessage.velocity)
}

// required int32 heading = 5;
inline bool targetMessage::has_heading() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void targetMessage::clear_heading() {
  heading_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::google::protobuf::int32 targetMessage::heading() const {
  // @@protoc_insertion_point(field_get:fusionPackage.targetMessage.heading)
  return heading_;
}
inline void targetMessage::set_heading(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000010u;
  heading_ = value;
  // @@protoc_insertion_point(field_set:fusionPackage.targetMessage.heading)
}

// required uint32 type = 6;
inline bool targetMessage::has_type() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void targetMessage::clear_type() {
  type_ = 0u;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::google::protobuf::uint32 targetMessage::type() const {
  // @@protoc_insertion_point(field_get:fusionPackage.targetMessage.type)
  return type_;
}
inline void targetMessage::set_type(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000020u;
  type_ = value;
  // @@protoc_insertion_point(field_set:fusionPackage.targetMessage.type)
}

// -------------------------------------------------------------------

// Timestamp

// required int64 seconds = 1;
inline bool Timestamp::has_seconds() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Timestamp::clear_seconds() {
  seconds_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int64 Timestamp::seconds() const {
  // @@protoc_insertion_point(field_get:fusionPackage.Timestamp.seconds)
  return seconds_;
}
inline void Timestamp::set_seconds(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  seconds_ = value;
  // @@protoc_insertion_point(field_set:fusionPackage.Timestamp.seconds)
}

// required int32 nanos = 2;
inline bool Timestamp::has_nanos() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Timestamp::clear_nanos() {
  nanos_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int32 Timestamp::nanos() const {
  // @@protoc_insertion_point(field_get:fusionPackage.Timestamp.nanos)
  return nanos_;
}
inline void Timestamp::set_nanos(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  nanos_ = value;
  // @@protoc_insertion_point(field_set:fusionPackage.Timestamp.nanos)
}

// -------------------------------------------------------------------

// fusionMsg

// required .fusionPackage.Timestamp timeStamp = 1;
inline bool fusionMsg::has_timestamp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void fusionMsg::clear_timestamp() {
  if (timestamp_ != nullptr) timestamp_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::fusionPackage::Timestamp& fusionMsg::timestamp() const {
  const ::fusionPackage::Timestamp* p = timestamp_;
  // @@protoc_insertion_point(field_get:fusionPackage.fusionMsg.timeStamp)
  return p != nullptr ? *p : *reinterpret_cast<const ::fusionPackage::Timestamp*>(
      &::fusionPackage::_Timestamp_default_instance_);
}
inline ::fusionPackage::Timestamp* fusionMsg::release_timestamp() {
  // @@protoc_insertion_point(field_release:fusionPackage.fusionMsg.timeStamp)
  _has_bits_[0] &= ~0x00000001u;
  ::fusionPackage::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline ::fusionPackage::Timestamp* fusionMsg::mutable_timestamp() {
  _has_bits_[0] |= 0x00000001u;
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::fusionPackage::Timestamp>(GetArenaNoVirtual());
    timestamp_ = p;
  }
  // @@protoc_insertion_point(field_mutable:fusionPackage.fusionMsg.timeStamp)
  return timestamp_;
}
inline void fusionMsg::set_allocated_timestamp(::fusionPackage::Timestamp* timestamp) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete timestamp_;
  }
  if (timestamp) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      timestamp = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:fusionPackage.fusionMsg.timeStamp)
}

// repeated .fusionPackage.targetMessage msg = 2;
inline int fusionMsg::msg_size() const {
  return msg_.size();
}
inline void fusionMsg::clear_msg() {
  msg_.Clear();
}
inline ::fusionPackage::targetMessage* fusionMsg::mutable_msg(int index) {
  // @@protoc_insertion_point(field_mutable:fusionPackage.fusionMsg.msg)
  return msg_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::fusionPackage::targetMessage >*
fusionMsg::mutable_msg() {
  // @@protoc_insertion_point(field_mutable_list:fusionPackage.fusionMsg.msg)
  return &msg_;
}
inline const ::fusionPackage::targetMessage& fusionMsg::msg(int index) const {
  // @@protoc_insertion_point(field_get:fusionPackage.fusionMsg.msg)
  return msg_.Get(index);
}
inline ::fusionPackage::targetMessage* fusionMsg::add_msg() {
  // @@protoc_insertion_point(field_add:fusionPackage.fusionMsg.msg)
  return msg_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::fusionPackage::targetMessage >&
fusionMsg::msg() const {
  // @@protoc_insertion_point(field_list:fusionPackage.fusionMsg.msg)
  return msg_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace fusionPackage

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_fusion_2eproto
